Rotation
StudyUnity-Organization/StudyUnityGameCube pull request #2
Opened 2023-11-25 13:16 UTC by COBRA445

2023-11-25 15:22 UTC, Gr871 requested changes

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/LogicScript.cs
> +    //TODO �������� � UI ����� ��������� ���� � ����� + �����? ���?
Посмотри на кодировку. Должна быть  UTF-8. Это стандарт.
Погугли, как "настроить кодировку в VisualStudio"

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/LogicScript.cs
> +    public cubeScript cubeScript;
Наименование не по феншую. 2 момента:
1. Наименование скрипта `cubeScript`: наименование скриптов с большой буквы. 
2. Наименование переменной `cubeScript`: так же с большой буквы, так как она публичная

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/LogicScript.cs
> +    private int randomX_Highest = 25;
Наименование переменных некорректно. См. доку

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/LogicScript.cs
> +        spawnCubeGeneator();
Наименование функции - некорректное

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/LogicScript.cs
> +        Instantiate(CubeGenerator, new Vector3(UnityEngine.Random.Range(randomX_Highest, randomX_Lowest), 0, UnityEngine.Random.Range(randomZ_Highest, randomZ_Lowest)), transform.rotation);
Если есть риск перепутать с другим пространством имен (например, `UnityEngine.Random` и `System.Random`),  то в начали скрипта можно указать конкретный вариант использования (например, `using Random = UnityEngine.Random;`

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/LogicScript.cs
> +        Instantiate(CubeGenerator, new Vector3(UnityEngine.Random.Range(randomX_Highest, randomX_Lowest), 0, UnityEngine.Random.Range(randomZ_Highest, randomZ_Lowest)), transform.rotation);
Это делается для того, чтобы в скриптах не тянуть длинные названия

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/LogicScript.cs
> +        UIScript.GameOver(score);
`UIScript` не по феншую. В аббревиатурах с Заглавной буквы идет только первая (так что, `UiScript`)

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/LogicScript.cs
> +    public void restartGame() {
не по феншую

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/UIScript.cs
> +    private float timesTimer = 0;  //���������� ��� ��������
Наименование приватных переменных не по феншую (должно начинаться с `_`, например,  `_score`)

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/UIScript.cs
> +    }
Если функция бесполезная  - не нужно ее объявлять. Особенно это касается функций `Monobehaviour`'a

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/UIScript.cs
> +    public Text textBestRresults;
Не по феншую

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/UIScript.cs
> +            else {
в одну строку

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/UIScript.cs
> +    public void searchBestResult() {
Разделяй минимум одной строкой объявления фнукций. А желаетльно, еще комментарии добавлять к каждой

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/cubeScript.cs
> +    public void cube_Move(bool can) {
Наименование переменной

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/cubeScript.cs
> +                                                 transform.position.z + transform.forward.z * speed * Time.deltaTime);
С выравниванием беда

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/cubeSpawnerScrip.cs
> +public class cubeSpawnerScrip : MonoBehaviour {
Наименование класса не по феншую

2023-11-25 15:22 UTC, Gr871 commented on Assets/Scripts/cubeSpawnerScrip.cs
> +    void Update() {
пустой скрипт ни к чему

2023-12-04 06:15 UTC, Gr871 requested changes

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/LogicScript.cs
> +    private float kRotation = 0;
приватные несериализуемые перменные начинаются с "_": `_kDistance`

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/LogicScript.cs
> +    private float kRotation = 0;
второй момент что `k` вносит некий деструктив в именование. Я так понимаю, что речь идет о "коэффициенте", которые в переводе на английский - `ratio` или `aspect`

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/LogicScript.cs
> +    private float kRotation = 0;
должно получиться, например, `_distanseAspect` или `_distanceRatio`.

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/LogicScript.cs
> +    private float angleBeetwenCubeAndCubeClone = 0;
А зачем тебе эта переменная? я, во-первых, не вижу ее использование, а во-вторых, сериализация нужна тогда, когда ты хочешь изменять параметр из эдитора руками (ну или в крайнем случае вывести для отладки в него же). Думаю, что здесь тебе "УЖЕ" это не требуется

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/LogicScript.cs
> +    private GameObject CubeGeneratorClone;
Давай разбираться с наименованиями:
1. Что такого `CubeGenerator`? из названия следует, что это объект, который самостоятельно решает задачу генерации каких-то кубов. А я подозреваю, что это лишь "основа" для генерации **цели** (**префаб**, с которого скрипт в одной из функци ниже создает копию). Так тогда давай и переименуем эту переменную в `TargetSourcePrefab`, например, и будет понятно, что это "префаб-источник" для создания цели.
2. а зачем тебе эта переменная публичная? может достаточно сделать ее приватной и `[SerializedField]`?

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/LogicScript.cs
> +    private GameObject CubeGeneratorClone;
Отсюда `CubeGeneratorClone` (к слову, напоминаю, что приватные переменные именуются не так) название не корректное. Суффикс `Clone`, в целом, как-то да отражает суть. Но куда логичнее вместо `Clone` использовать `Instance` и тогда однозначно понятно, что `targetInstance` - это "цель", конкретный "экземпляр" объекта `TargetSourcePrefab`

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/MathLib/Interpolation.cs
> +public class Interpolation {
красота. Вроде как по всем канонам)

внизу тока подрежь кол-во пустых строк

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/MathLib/Trigonometry.cs
> +﻿public class Trigonometry {
ну думаю, что нужен этот скрипт

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/MathLib/Vector3D.cs
> +        */
Выпиливай, что не используется
А так - тоже конфетка

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/UIScript.cs
> +    private float timesTimer = 0;  //���������� ��� ��������
+ Смотри, что с комментариями. Опять кодировка не корректная

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/UIScript.cs
> +            // Debug.Log("text color " + red + "  " + green + "  " + blue); // ������ ���� ����������� ���������� � ������ ���� - ������
не нужные строки - удаляй

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/UIScript.cs
> +                //  Debug.log("TIME: " + time_temporary2);
не нужные строки

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/cubeScript.cs
> +public class cubeScript : MonoBehaviour {
Наименование скрипта

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/cubeScript.cs
> +        logic.�hanging�olor();
ну тут какие-то фантастические имена

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/cubeScript.cs
> +        logic.�hanging�olor();
а, знаю: это `C` русская

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/cubeScript.cs
> +
пустые и ненужные строки

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/cubeScript.cs
> +    //}
не нужные строки

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/indicator.cs
> +    public void �hanging�olorDistance(float distance, float rotation) {
Как ты умудряешься такие именования фигачить?)

2023-12-04 06:15 UTC, Gr871 commented on Assets/Scripts/indicator.cs
> +        //button.GetComponent<Image>().color = color;
пустые строки

2023-12-04 11:16 UTC, COBRA445 commented on Assets/Scripts/LogicScript.cs
> +        spawnCubeGeneator();
Я поправил это...видимо не залил изменения(хотя вроде заливал...)

2023-12-04 11:29 UTC, COBRA445 commented on Assets/Scripts/cubeScript.cs
> +    public void cube_Move(bool can) {
Тоже пофиксил, но не залил

2023-12-04 11:29 UTC, COBRA445 commented on Assets/Scripts/cubeScript.cs
> +                                                 transform.position.z + transform.forward.z * speed * Time.deltaTime);
Почему? Я же здесь специально так разделил, чтою переменные (передаваемые в конструктор) были друг под другом

2023-12-04 11:35 UTC, COBRA445 commented on Assets/Scripts/indicator.cs
> +    public void �hanging�olorDistance(float distance, float rotation) {
Что-то я сам в шоке....

2023-12-05 06:08 UTC, Gr871 commented on Assets/Scripts/cubeScript.cs
> +                                                 transform.position.z + transform.forward.z * speed * Time.deltaTime);
не, сейчас все ровно
этот комментарий, видимо, еще от старого варианта остался

Когда исправил - жми Resolve, чтобы таких эксцессов не было

2023-12-06 05:42 UTC, closed without merging